services:

  builder:
    build: .
    env_file:
      - path: .env.builder
        required: false
    privileged: true
    pull_policy: never
    volumes:
      - ./:/workspace/
    working_dir: /workspace
